Map<String, String> countries = {
  "Afghanistan": "+93",
  "Albania": "+355",
  "Algeria": "+213",
  "American Samoa": "+1 684",
  "Andorra": "+376",
  "Angola": "+244",
  "Anguilla": "+1 264",
  "Antarctica": "+1",
  "Antigua and Barbuda": "+1 268",
  "Argentina": "+54",
  "Armenia": "+374",
  "Aruba": "+297",
  "Australia": "+61",
  "Austria": "+43",
  "Azerbaijan": "+994",
  "Bahamas": "+1 242",
  "Bahrain": "+973",
  "Bangladesh": "+880",
  "Barbados": "+1 246",
  "Belarus": "+375",
  "Belgium": "+32",
  "Belize": "+501",
  "Benin": "+229",
  "Bermuda": "+1 441",
  "Bhutan": "+975",
  "Bolivia, Plurinational State of": "+591",
  "Bonaire, Sint Eustatius and Saba": "+599 7",
  "Bosnia and Herzegovina": "+387",
  "Botswana": "+267",
  "Bouvet Island": "+1",
  "Brazil": "+55",
  "British Indian Ocean Territory": "+246",
  "Brunei Darussalam": "+673",
  "Bulgaria": "+359",
  "Burkina Faso": "+226",
  "Burundi": "+257",
  "Denmark": "+45",
  "Djibouti": "+253",
  "Dominica": "+1 767",
  "Dominican Republic": "+1 809, +1 829, +1 849",
  "Ecuador": "+593",
  "Egypt": "+20",
  "El Salvador": "+503",
  "Equatorial Guinea": "+240",
  "Eritrea": "+291",
  "Estonia": "+372",
  "Ethiopia": "+251",
  "Falkland Islands (Malvinas)": "+500",
  "Faroe Islands": "+298",
  "Fiji": "+679",
  "Finland": "+358",
  "France": "+33",
  "French Guiana": "+594",
  "French Polynesia": "+689",
  "Gabon": "+241",
  "Gambia": "+220",
  "Germany": "+49",
  "Ghana": "+233",
  "Gibraltar": "+350",
  "Greece": "+30",
  "Greenland": "+299",
  "Grenada": "+1 473",
  "Guadeloupe": "+590",
  "Guam": "+1 671",
  "Guatemala": "+502",
  "Guernsey": "+44 1481",
  "Guinea": "+224",
  "Guinea-Bissau": "+245",
  "Guyana": "+592",
  "Haiti": "+509",
  "Heard Island and McDonald Islands": "+1",
  "Holy See (Vatican City State)": "+379",
  "Honduras": "+504",
  "Hong Kong": "+852",
  "Hungary": "+36",
  "Iceland": "+354",
  "India": "+91",
  "Indonesia": "+62",
  "Iran, Islamic Republic of": "+98",
  "Iraq": "+964",
  "Ireland": "+353",
  "Isle of Man": "+44 1624",
  "Israel": "+972",
  "Italy": "+39",
  "Jamaica": "+1 876",
  "Japan": "+81",
  "Jersey": "+44 1534",
  "Jordan": "+962",
  "Kazakhstan": "+7",
  "Kenya": "+254",
  "Kiribati": "+686",
  "Korea, Democratic People's Republic of": "+850",
  "Korea, Republic of": "+82",
  "Kuwait": "+965",
  "Kyrgyzstan": "+996",
  "Lao People's Democratic Republic": "+856",
  "Latvia": "+371",
  "Libya": "+218",
  "Liechtenstein": "+423",
  "Lithuania": "+370",
  "Luxembourg": "+352",
  "Macao": "+853",
  "Macedonia, the former Yugoslav Republic of": "+389",
  "Madagascar": "+261",
  "Malawi": "+265",
  "Malaysia": "+60",
  "Maldives": "+960",
  "Mali": "+223",
  "Malta": "+356",
  "Marshall Islands": "+692",
  "Martinique": "+596",
  "Mauritania": "+222",
  "Mauritius": "+230",
  "Mayotte": "+262",
  "Mexico": "+52",
  "Micronesia, Federated States of": "+691",
  "Moldova, Republic of": "+373",
  "Monaco": "+377",
  "Mongolia": "+976",
  "Montenegro": "+382",
  "Montserrat": "+1 664",
  "Morocco": "+212",
  "Mozambique": "+258",
  "Myanmar": "+95",
  "Namibia": "+264",
  "Nauru": "+674",
  "Nepal": "+977",
  "Netherlands": "+31",
  "New Caledonia": "+687",
  "New Zealand": "+64",
  "Nicaragua": "+505",
  "Niger": "+227",
  "Nigeria": "+234",
  "Norfolk Island": "+672",
};

Map<String, String> countryImages = {
  "Afghanistan": "https://flagcdn.com/64x48/af.png",
  "Albania": "https://flagcdn.com/64x48/al.png",
  "Algeria": "https://flagcdn.com/64x48/dz.png",
  "American Samoa": "https://flagcdn.com/64x48/as.png",
  "Andorra": "https://flagcdn.com/64x48/ad.png",
  "Angola": "https://flagcdn.com/64x48/ao.png",
  "Anguilla": "https://flagcdn.com/64x48/ai.png",
  "Antarctica": "https://flagcdn.com/64x48/aq.png",
  "Antigua and Barbuda": "https://flagcdn.com/64x48/ag.png",
  "Argentina": "https://flagcdn.com/64x48/ar.png",
  "Armenia": "https://flagcdn.com/64x48/am.png",
  "Aruba": "https://flagcdn.com/64x48/aw.png",
  "Australia": "https://flagcdn.com/64x48/au.png",
  "Austria": "https://flagcdn.com/64x48/at.png",
  "Azerbaijan": "https://flagcdn.com/64x48/az.png",
  "Bahamas": "https://flagcdn.com/64x48/bs.png",
  "Bahrain": "https://flagcdn.com/64x48/bh.png",
  "Bangladesh": "https://flagcdn.com/64x48/bd.png",
  "Barbados": "https://flagcdn.com/64x48/bb.png",
  "Belarus": "https://flagcdn.com/64x48/by.png",
  "Belgium": "https://flagcdn.com/64x48/be.png",
  "Belize": "https://flagcdn.com/64x48/bz.png",
  "Benin": "https://flagcdn.com/64x48/bj.png",
  "Bermuda": "https://flagcdn.com/64x48/bm.png",
  "Bhutan": "https://flagcdn.com/64x48/bt.png",
  "Bolivia": "https://flagcdn.com/64x48/bo.png",
  "Bosnia and Herzegovina": "https://flagcdn.com/64x48/ba.png",
  "Botswana": "https://flagcdn.com/64x48/bw.png",
  "Brazil": "https://flagcdn.com/64x48/br.png",
  "British Indian Ocean Territory": "https://flagcdn.com/64x48/io.png",
  "British Virgin Islands": "https://flagcdn.com/64x48/vg.png",
  "Brunei": "https://flagcdn.com/64x48/bn.png",
  "Bulgaria": "https://flagcdn.com/64x48/bg.png",
  "Burkina Faso": "https://flagcdn.com/64x48/bf.png",
  "Burundi": "https://flagcdn.com/64x48/bi.png",
  "Democratic Republic of the Congo": "https://flagcdn.com/64x48/cd.png",
  "Denmark": "https://flagcdn.com/64x48/dk.png",
  "Djibouti": "https://flagcdn.com/64x48/dj.png",
  "Dominica": "https://flagcdn.com/64x48/dm.png",
  "Dominican Republic": "https://flagcdn.com/64x48/do.png",
  "East Timor": "https://flagcdn.com/64x48/tl.png",
  "Ecuador": "https://flagcdn.com/64x48/ec.png",
  "Egypt": "https://flagcdn.com/64x48/eg.png",
  "El Salvador": "https://flagcdn.com/64x48/sv.png",
  "Equatorial Guinea": "https://flagcdn.com/64x48/gq.png",
  "Eritrea": "https://flagcdn.com/64x48/er.png",
  "Estonia": "https://flagcdn.com/64x48/ee.png",
  "Eswatini": "https://flagcdn.com/64x48/sz.png",
  "Ethiopia": "https://flagcdn.com/64x48/et.png",
  "Falkland Islands": "https://flagcdn.com/64x48/fk.png",
  "Faroe Islands": "https://flagcdn.com/64x48/fo.png",
  "Fiji": "https://flagcdn.com/64x48/fj.png",
  "Finland": "https://flagcdn.com/64x48/fi.png",
  "France": "https://flagcdn.com/64x48/fr.png",
  "French Guiana": "https://flagcdn.com/64x48/gf.png",
  "French Polynesia": "https://flagcdn.com/64x48/pf.png",
  "Gabon": "https://flagcdn.com/64x48/ga.png",
  "Gambia": "https://flagcdn.com/64x48/gm.png",
  "Germany": "https://flagcdn.com/64x48/de.png",
  "Ghana": "https://flagcdn.com/64x48/gh.png",
  "Gibraltar": "https://flagcdn.com/64x48/gi.png",
  "Greece": "https://flagcdn.com/64x48/gr.png",
  "Greenland": "https://flagcdn.com/64x48/gl.png",
  "Grenada": "https://flagcdn.com/64x48/gd.png",
  "Guadeloupe": "https://flagcdn.com/64x48/gp.png",
  "Guam": "https://flagcdn.com/64x48/gu.png",
  "Guatemala": "https://flagcdn.com/64x48/gt.png",
  "Guernsey": "https://flagcdn.com/64x48/gg.png",
  "Guinea": "https://flagcdn.com/64x48/gn.png",
  "Guinea-Bissau": "https://flagcdn.com/64x48/gw.png",
  "Guyana": "https://flagcdn.com/64x48/gy.png",
  "Haiti": "https://flagcdn.com/64x48/ht.png",
  "Honduras": "https://flagcdn.com/64x48/hn.png",
  "Hong Kong": "https://flagcdn.com/64x48/hk.png",
  "Hungary": "https://flagcdn.com/64x48/hu.png",
  "Iceland": "https://flagcdn.com/64x48/is.png",
  "India": "https://flagcdn.com/64x48/in.png",
  "Indonesia": "https://flagcdn.com/64x48/id.png",
  "Iran": "https://flagcdn.com/64x48/ir.png",
  "Iraq": "https://flagcdn.com/64x48/iq.png",
  "Ireland": "https://flagcdn.com/64x48/ie.png",
  "Isle of Man": "https://flagcdn.com/64x48/im.png",
  "Israel": "https://flagcdn.com/64x48/il.png",
  "Italy": "https://flagcdn.com/64x48/it.png",
  "Ivory Coast": "https://flagcdn.com/64x48/ci.png",
  "Jamaica": "https://flagcdn.com/64x48/jm.png",
  "Japan": "https://flagcdn.com/64x48/jp.png",
  "Jersey": "https://flagcdn.com/64x48/je.png",
  "Jordan": "https://flagcdn.com/64x48/jo.png",
  "Kazakhstan": "https://flagcdn.com/64x48/kz.png",
  "Kenya": "https://flagcdn.com/64x48/ke.png",
  "Kiribati": "https://flagcdn.com/64x48/ki.png",
  "Kosovo": "https://flagcdn.com/64x48/xk.png",
  "Kuwait": "https://flagcdn.com/64x48/kw.png",
  "Kyrgyzstan": "https://flagcdn.com/64x48/kg.png",
  "Laos": "https://flagcdn.com/64x48/la.png",
  "Latvia": "https://flagcdn.com/64x48/lv.png",
  "Lebanon": "https://flagcdn.com/64x48/lb.png",
  "Lesotho": "https://flagcdn.com/64x48/ls.png",
  "Liberia": "https://flagcdn.com/64x48/lr.png",
  "Libya": "https://flagcdn.com/64x48/ly.png",
  "Liechtenstein": "https://flagcdn.com/64x48/li.png",
  "Lithuania": "https://flagcdn.com/64x48/lt.png",
  "Luxembourg": "https://flagcdn.com/64x48/lu.png",
  "Macau": "https://flagcdn.com/64x48/mo.png",
  "Madagascar": "https://flagcdn.com/64x48/mg.png",
  "Malawi": "https://flagcdn.com/64x48/mw.png",
  "Malaysia": "https://flagcdn.com/64x48/my.png",
  "Maldives": "https://flagcdn.com/64x48/mv.png",
  "Mali": "https://flagcdn.com/64x48/ml.png",
  "Malta": "https://flagcdn.com/64x48/mt.png",
  "Marshall Islands": "https://flagcdn.com/64x48/mh.png",
  "Martinique": "https://flagcdn.com/64x48/mq.png",
  "Mauritania": "https://flagcdn.com/64x48/mr.png",
  "Mauritius": "https://flagcdn.com/64x48/mu.png",
  "Mayotte": "https://flagcdn.com/64x48/yt.png",
  "Mexico": "https://flagcdn.com/64x48/mx.png",
  "Micronesia": "https://flagcdn.com/64x48/fm.png",
  "Moldova": "https://flagcdn.com/64x48/md.png",
  "Monaco": "https://flagcdn.com/64x48/mc.png",
  "Mongolia": "https://flagcdn.com/64x48/mn.png",
  "Montenegro": "https://flagcdn.com/64x48/me.png",
  "Montserrat": "https://flagcdn.com/64x48/ms.png",
  "Morocco": "https://flagcdn.com/64x48/ma.png",
  "Mozambique": "https://flagcdn.com/64x48/mz.png",
  "Myanmar": "https://flagcdn.com/64x48/mm.png",
  "Namibia": "https://flagcdn.com/64x48/na.png",
  "Nauru": "https://flagcdn.com/64x48/nr.png",
  "Nepal": "https://flagcdn.com/64x48/np.png",
  "Netherlands": "https://flagcdn.com/64x48/nl.png",
  "New Caledonia": "https://flagcdn.com/64x48/nc.png",
  "New Zealand": "https://flagcdn.com/64x48/nz.png",
  "Nicaragua": "https://flagcdn.com/64x48/ni.png",
  "Niger": "https://flagcdn.com/64x48/ne.png",
  "Nigeria": "https://flagcdn.com/64x48/ng.png",
  "Niue": "https://flagcdn.com/64x48/nu.png",
  "Norfolk Island": "https://flagcdn.com/64x48/nf.png",
};
